Description: Creates Airflow Webserver Service

Resources:
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "dbt-production-ecs-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "ECSTaskRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "*"
                Resource: "*"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !Ref ECSTaskRole
      TaskRoleArn: !Ref ECSTaskRole
      Family: "production-dbt-image"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: "production-dbt-image"
          Image: !Sub
            - "${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/production-dbt-image:latest"
            - ecr_repository: dbt-image
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: airflow-production-ecs-log-group
              awslogs-region: us-east-1
              awslogs-stream-prefix: dbt-image

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Airflow webserver. Allow all inbound traffic.
      GroupName: "dbt-security-group"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: 0
          IpProtocol: -1
          ToPort: 0
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 0
          IpProtocol: -1
          ToPort: 0
      VpcId: vpc-0b80e484ad754b405


Outputs:
  SecurityGroup:
    Value: !Ref SecurityGroup
